### PR TITLE
Fix broken h1stats due to CSRF token requirement, plus other tweaks

### PR DESCRIPTION
**Pull request by h1pmnh**
Sorry for the messy commit history, let me know if you want a cleaner PR and I'll re-fork my repo.

Primary reason for this PR is that HackerOne changed their GraphQL endpoint to require a CSRF token in the header, so the `h1stats` tool has been broken for some time now.

I also made a couple quality of life changes:
 * Removed the Base64 encoded GraphQL query and used heredoc syntax instead for easier merging/contributions
 * Removed (partially) the code for public (non-authenticated) mode since H1 doesn't support this anymore
 * Added collaboration yes/no column to export

Thanks!
Peter

### CODE REVIEW

**Comment by defparam** [comment]
Thanks for keeping this software alive. Once I test it I'll merge it in. Thanks!

**Comment by h1pmnh** [comment]
Honestly I forgot this was open :D let me know if you want me to clean anything up.

**Comment by defparam** [comment]
_looks good, but unfortunately for me (unless I did something wrong) the graphql query only pulls public programs even with the cookie specified. It appears the private programs are separated into a separate query but I'm not sure at this moment how to batch them in groups of 50. I'm not the best at creating custom queries, hopefully someone can figure it out or we just pull private program information 1 query at a time and batch them across 10-40 threads._ 

EDIT: my mistake, this query does still work for both public and private, I just put my creds in incorrectly. However like i mentioned in my comment below, public-only doesn't require auth

**Comment by defparam** [comment]
Also I'm not sure why you say an auth session is needed for public programs, it doesn't appear that way

image

**Comment by defparam** [comment]
All set @h1pmnh ! I added your fixes and I tweaked a couple things to place back public mode. Looks to be working again. 

Thanks!

**Comment by h1pmnh** [comment]
Awesome 👍 thank you!
-------- Original message --------From: Evan ***@***.***> Date: 7/2/23  4:59 PM  (GMT-05:00) To: defparam/h1stats ***@***.***> Cc: ***@***.***" ***@***.***>, Mention ***@***.***> Subject: Re: [defparam/h1stats] Fix broken h1stats due to CSRF token
  requirement, plus other tweaks (PR #3) 
All set @h1pmnh ! I added your fixed and I tweaked a couple things to place back public mode. Looks to be working again.
Thanks!

**Pull request merged**
